# sendairk03 の Rakefile。定数と helper、そして aggregate task (test / default) だけ。個別の task は rakelib/。
#
# 開発 harness (bash0C7/R2P2-dev-harness) は vendor/R2P2-dev-harness に clone して
# そのまま使う。harness の rakelib は HARNESS_ROOT を基準に gems/ build_config/
# examples/ build/ を見るので、ここで HARNESS_ROOT を本 repo の root にしてから
# harness の rakelib を load する。harness の Rakefile 自体は load しない
# (定数の二重定義と default task の持ち込みを避ける)。
require "fileutils"
require "digest"
require "shellwords"
require "rbconfig"

HARNESS_ROOT  = __dir__
VENDOR_DIR    = File.join(HARNESS_ROOT, "vendor")
BUILD_DIR     = File.join(HARNESS_ROOT, "build")

# 1 本目の picoruby tree: host test と wasm が使う。常に最新 (master)。
PICORUBY_SRC  = File.join(VENDOR_DIR, "picoruby")
PICORUBY_REPO = ENV["PICORUBY_REPO"] || "https://github.com/picoruby/picoruby.git"
PICORUBY_REF  = ENV["PICORUBY_REF"]  || "master"

HARNESS_REPO = ENV["HARNESS_REPO"] || "https://github.com/bash0C7/R2P2-dev-harness.git"
HARNESS_REF  = ENV["HARNESS_REF"]  || "main"
HARNESS_DIR  = File.join(VENDOR_DIR, "R2P2-dev-harness")

# 2 本目: R2P2-ESP32 が submodule として持つ picoruby。pin は上流の submodule に従う
# (「常に最新」は 1 本目にだけ適用する。ESP32 の CMake は submodule の tree と結合している)。
ESP32_REPO     = ENV["ESP32_REPO"] || "https://github.com/picoruby/R2P2-ESP32.git"
ESP32_REF      = ENV["ESP32_REF"]  || "master"
ESP32_DIR      = File.join(VENDOR_DIR, "R2P2-ESP32")
ESP32_PICORUBY = File.join(ESP32_DIR, "components", "picoruby-esp32", "picoruby")

# 3 本目: R2P2-darwin が vendor に取る fork (bash0C7/picoruby の port-darwin)。
DARWIN_REPO     = ENV["DARWIN_REPO"] || "https://github.com/bash0C7/R2P2-darwin.git"
DARWIN_REF      = ENV["DARWIN_REF"]  || "main"
DARWIN_DIR      = File.join(VENDOR_DIR, "R2P2-darwin")
DARWIN_PICORUBY = File.join(DARWIN_DIR, "vendor", "picoruby")

# host build に入る = test:host / test:host_femto が回す gem。
# target 専用の gem をここに入れると build_config/host-test.rb 経由で host build が壊れる。
HARNESS_GEMS = %w[
  picoruby-instrument-frame
  picoruby-instrument
  picoruby-instrument-link
].freeze

# build_config 側でだけ足す gem (host では compile しない / できない)。
TARGET_ONLY_GEMS = %w[
  picoruby-serialport
  picoruby-drb-ble
  picoruby-darwin-synth
].freeze

# harness の rakelib/vendor.rake がそのまま使う。名前も値も harness と同じにする。
OVERLAY_TARGET    = "build_config/r2p2-picoruby-pico2_w.rb".freeze
OVERLAY_PRESERVED = "build_config/r2p2-picoruby-pico2_w.upstream.rb".freeze
OVERLAY_MARKER    = "# generated by R2P2-dev-harness".freeze

HOST_SUBMODULES = %w[
  mrbgems/picoruby-mruby/lib/mruby
  mrbgems/picoruby-mrubyc/lib/mrubyc
  mrbgems/mruby-compiler
  mrbgems/mruby-bin-mrbc
  mrbgems/picoruby-machine/lib/estalloc
  mrbgems/picoruby-regexp_light/lib/regex_light
  mrbgems/picoruby-littlefs/lib/littlefs
  mrbgems/picoruby-funicular
].freeze

# harness は Pico 2 W の heap 対策で compiler を旧 pin に固定するが、本 repo は同じ vendor/picoruby を
# host test と wasm が使うので pin しない。
# upstream の pico2_w config が MRC_PRISM_ARENA_BLOCK=2048 を define しているので pin 無しで足りる
# (mruby-compiler/src/ccontext.c の #ifndef)。
SUBMODULE_PINS = {}.freeze

# ESP32: vendor 内の build_config (CMake が path を決め打つ) => 本 repo の build_config。
# harness の vendor:overlay と同じ shim 方式。
ESP32_OVERLAYS = {
  "components/picoruby-esp32/build_config/xtensa-esp-femtoruby.rb" => "esp32-atom-femtoruby.rb",
  "components/picoruby-esp32/build_config/xtensa-esp-picoruby.rb"  => "esp32-atom-picoruby.rb"
}.freeze
ESP32_OVERLAY_MARKER = "# generated by sendairk03".freeze
# mrubyc = FemtoRuby (ATOM Matrix の既定) / mruby = PicoRuby (S3 系、ATOM では spike のみ)
ESP32_VM     = ENV["PICORB_VM"]  || "mrubyc"
ESP32_TARGET = ENV["IDF_TARGET"] || "esp32"

def vendor_ready?
  File.directory?(File.join(PICORUBY_SRC, ".git"))
end

def require_vendor!
  return if vendor_ready?
  raise "vendor/picoruby is not there. Run `rake vendor:setup_all` (or `rake setup`) first."
end

def harness_ready?
  File.directory?(File.join(HARNESS_DIR, "rakelib"))
end

def require_harness!
  return if harness_ready?
  raise "vendor/R2P2-dev-harness is not there. Run `rake vendor:setup_all` first."
end

# 子プロセスの PATH にも rake の exe が要る (upstream の task が裸の rake を呼ぶ)。
def rake_command
  rake = begin
           Gem.bin_path("rake", "rake")
         rescue StandardError
           nil
         end
  [rake ? "#{RbConfig.ruby.shellescape} #{rake.shellescape}" : "rake", rake]
end

def rake_in(dir, env, *args)
  command, rake = rake_command
  child_env = env.dup
  child_env["PATH"] = [File.dirname(rake), ENV["PATH"]].compact.join(File::PATH_SEPARATOR) if rake
  FileUtils.cd(dir) do
    sh child_env, "#{command} #{args.map(&:shellescape).join(' ')}"
  end
end

def vendor_rake(env, *args)
  require_vendor!
  rake_in(PICORUBY_SRC, env, *args)
end

# ESP-IDF を subshell で有効化してから vendor/R2P2-ESP32 の中で実行する。esp32.rake の esp32:run も
# (プロセスの生存を自分で見るために) この文字列組み立てだけを使う。
def esp_shell_command(cmd)
  idf = ENV["IDF_PATH"] || File.expand_path("~/esp/esp-idf")
  export = File.join(idf, "export.sh")
  raise "ESP-IDF not found: #{export} (set IDF_PATH)" unless File.exist?(export)
  ". #{export.shellescape} >/dev/null && cd #{ESP32_DIR.shellescape} && #{cmd}"
end

def esp_sh(cmd, env = {})
  sh env, "bash", "-lc", esp_shell_command(cmd)
end

# harness の rakelib のうち vendor.rake と test.rake だけを load する
# (rp2040.rake は rakelib/rp2040.rake が別途 guard して load する)。
def load_harness_rakelib!
  return unless harness_ready?
  return if $sendairk03_harness_loaded
  $sendairk03_harness_loaded = true
  %w[vendor.rake test.rake].each do |f|
    load File.join(HARNESS_DIR, "rakelib", f)
  end
end

load_harness_rakelib!

desc "板なしで確かめられる全部 (host picotest 両 VM + example / web / server の compile)"
task test: %w[test:host test:examples test:sources test:gem_lists test:host_femto]

task default: [:test]
